[deploy]
startCommand = "gunicorn mental_wellness.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.11.11"
DJANGO_DEBUG = "False"
WEB_CONCURRENCY = "1"
PYTORCH_CUDA_ALLOC_CONF = "max_split_size_mb:512"
TRANSFORMERS_CACHE = "/tmp/transformers_cache"
HF_HOME = "/tmp/huggingface"
HF_DATASETS_CACHE = "/tmp/huggingface/datasets"
HF_METRICS_CACHE = "/tmp/huggingface/metrics"
HF_MODULES_CACHE = "/tmp/huggingface/modules" 