services:
  - type: web
    name: mental-wellness
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mental_wellness.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true 