services:
  - type: web
    name: mental-wellness
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mental_wellness.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: WEB_CONCURRENCY
        value: 4 