# Generated by Django 5.0.2 on 2025-05-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_breathingexercise_meditationsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meditationsession',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='meditationsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='selfcaresuggestion',
            name='user',
        ),
        migrations.DeleteModel(
            name='BreathingExercise',
        ),
        migrations.DeleteModel(
            name='MeditationSession',
        ),
        migrations.DeleteModel(
            name='SelfCareSuggestion',
        ),
    ]
