# Generated by Django 5.0.2 on 2025-05-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_breathingexercise_meditationsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfcaresuggestion',
            name='duration',
            field=models.CharField(default='15 minutes', max_length=50),
        ),
        migrations.AddField(
            model_name='selfcaresuggestion',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
